import esbuild from "esbuild"
import process from "process"
import builtins from "builtin-modules"

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = (process.argv[2] === "production")

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// ! 入口点，就是 main.ts 的相对对路径
	entryPoints: ["src/main.ts"],
	bundle: true,  // 打包成单文件
	minify: true, // 极致压缩
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	// format: "iife",  // 立即执行函数，压缩更极致
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}