import esbuild from "esbuild"
import process from "process"
import builtins from "builtin-modules"

import fs from "fs"
import path from "path"

// const copyTargetDir = "D:\\Self\\notes\\Work\\.obsidian\\plugins\\cyu-tool-kit"
const copyTargetDir = "E:/OB vault/Sensual-art/.obsidian/plugins/cyu-tool-kit"

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = (process.argv[2] === "production")

// 定义一个简单的复制插件
const copyToTargetPlugin = {
	name: 'copy-to-target',
	setup(build) {
		build.onEnd(() => {
			try {
				// 如果目标目录不存在则创建
				if (!fs.existsSync(copyTargetDir)) {
					fs.mkdirSync(copyTargetDir, { recursive: true })
				}

				// 需要复制的文件列表
				const filesToCopy = ["main.js", "styles.css", "manifest.json"]

				filesToCopy.forEach(file => {
					if (fs.existsSync(file)) {
						fs.copyFileSync(file, path.join(copyTargetDir, file))
					}
				})

				console.log(`[Custom] Files copied to: ${copyTargetDir}`)
			} catch (err) {
				console.error(`[Custom] Copy failed: ${err}`)
			}
		})
	},
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// ! 入口点，就是 main.ts 的相对对路径
	entryPoints: ["src/main.ts"],
	bundle: true,  // 打包成单文件
	minify: true, // 极致压缩
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	// format: "iife",  // 立即执行函数，压缩更极致
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	// 将插件添加到配置中
	// plugins: [copyToTargetPlugin],
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}